### ISSUE TITLE
API Ratings GET not working

### ISSUE THREAD

**Issue by ubdu** [kartevonmorgen/openfairdb#224] opened 2019-12-16 09:07 UTC
Using the Request URL https://api.ofdb.io/v0/ratings/<ID-String> you always get an empty result, although there are ratings for the requested place.

**Comment by uklotzde** [comment] 2019-12-16 17:08
The request expects *rating ids*, not *entry ids*.

**Comment by uklotzde** [comment] 2020-01-10 13:21
I will close this issue since it works as intended.

**Closed as completed by uklotzde** 2020-01-10 13:21 UTC
