### ISSUE TITLE
API for checking duplicates

### ISSUE THREAD

**Issue by naturzukunft** [kartevonmorgen/openfairdb#257] opened 2020-03-26 17:22 UTC
/ duplicates has as parameter (id, id) there should also be the possibility to pass (entry, id) so that you can check before you create an entry.
As a workaround you could create an entry and then set the status "rejected" if it was a duplicate.
It would be good if PUT / entries were included in the swagger / openAPI description. And the entry type gets a "status" field.

**Comment by naturzukunft** [comment] 2020-04-17 15:43
...and if you implement this interface, you should also think about calling this in a batch. Means passing a list of "entryId, entry, id" and getting a list of (entryId, result).

**Comment by wellemut** [comment] 2020-04-17 15:48
Possible duplicate of https://github.com/kartevonmorgen/openfairdb/issues/254
But this issues has a detailed question, so i levae it open.

**Comment by flosse** [comment] 2020-05-21 11:26
@naturzukunft and @navid-kalaei I'm going to create a branch to start with an implementation for an extended API

**Comment by wellemut** [comment] 2020-05-28 15:54
Similar https://github.com/kartevonmorgen/openfairdb/issues/254

**Comment by uklotzde** [comment] 2020-08-13 10:54
Done: #277

**Closed as completed by uklotzde** 2020-08-13 10:54 UTC
Labels: enhancement, 0 API, 21 backend

**Comment by wellemut** [comment] 2021-01-13 10:55
Just for Documentation: Check out the openfairDB-Yaml on swagger to see how it is working
![grafik](https://user-images.githubusercontent.com/15019030/104442990-1c1c3c80-5596-11eb-94bf-3e0b679092cc.png)

    go to https://editor.swagger.io
    go to File -> import URL
    enter https://raw.githubusercontent.com/kartevonmorgen/openfairdb/master/openapi.yaml
    enjoy ;-)
