### ISSUE TITLE
Implement or document adding a new RatingComment to a Rating

### ISSUE THREAD

**Issue by miguelsan** [kartevonmorgen/openfairdb#246] opened 2020-02-11 13:25 UTC
The current documentation does not mention a way to add a Comment to a Rating. Please implement or, in case it is already possible, document it properly.

**Comment by wellemut** [comment] 2020-02-11 18:35
Decide about the way, how Anwers are saved (as new Child-ratings or as Comments) https://github.com/kartevonmorgen/openfairdb/issues/245#issuecomment-584776398

**Comment by wellemut** [comment] 2020-03-03 23:45
This is a duplicate of: https://github.com/kartevonmorgen/openfairdb/issues/245#issuecomment-594186609

**Closed as completed by wellemut** 2020-03-03 23:45 UTC
